<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\Admin\AdminLTE-3\**" />
    <Compile Remove="wwwroot\Admin\Metronic\**" />
    <Content Remove="wwwroot\Admin\AdminLTE-3\**" />
    <Content Remove="wwwroot\Admin\Metronic\**" />
    <EmbeddedResource Remove="wwwroot\Admin\AdminLTE-3\**" />
    <EmbeddedResource Remove="wwwroot\Admin\Metronic\**" />
    <None Remove="wwwroot\Admin\AdminLTE-3\**" />
    <None Remove="wwwroot\Admin\Metronic\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="wwwroot\Admin\css\" />
    <Folder Include="wwwroot\Files\Request_Documents\Elaw\Forms\" />
    <Folder Include="wwwroot\Files\Request_Documents\Mosanafat\" />
    <Folder Include="wwwroot\Files\Request_Documents\Delegations\" />
    <Folder Include="wwwroot\Files\Request_Documents\ResetPasswordRequestImage\" />
    <Folder Include="wwwroot\Files\Request_Documents\Publishing\" />
    <Folder Include="wwwroot\Admin\js\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Channels\AssociatedPresscCorrespondent.cshtml" />
    <None Include="Views\Channels\ChannelRepresentativeOfficeNewRequest.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business\Business.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\MOINFO_API\MOINFO_API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Areas\Admin\Views\Elaw\AddForm.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Areas\Admin\Views\Tourism\EditLicencesDetails.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Areas\Admin\Views\Tourism\RequestClassificationDetails.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\Tourism\PreApprovalDetails.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\Tourism\LicencesDetails.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\Tourism\ChangedataLicRequest.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Admin\assets\js\attachmentUpload.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
